### ISSUE TITLE
Issue when using option 1 (Start Server)

### ISSUE THREAD

**Issue by AppleManPS3** [neoneggplant/EggShell#3] opened 2016-12-13 20:44 UTC
- Using iPad 2 (64GB) with iOS 9.3.3

- I press option one and the program will crash after going though setting up the LPORT

- If the program does not crash, it will freeze and not do anything and has to be closed via Task Manager.

I don't know what this error is but it should be fixed.

**Comment by hmksq** [comment] 2016-12-13 21:34
Duplicate of #2

**Comment by neoneggplant** [comment] 2016-12-13 22:08
when if freezes, does it say "listening on port xxxx"? And can you elaborate on what happens when it crashes, error messages would be helpful

**Comment by AppleManPS3** [comment] 2016-12-14 00:00
It crashes/freezes when "Listening on port xxxx". When it crashes; it crashes. No errors, no message, nothing, the program just disappears.

**Comment by neoneggplant** [comment] 2016-12-14 02:36
if you think its freezing, it's not, its listening for the connect back on your iOS device

**Comment by AppleManPS3** [comment] 2016-12-14 17:05
What does that mean?

**Comment by Shugabuga** [comment] 2016-12-14 20:52
@AppleManPS3 It's waiting for your iPhone to connect to EggShell. Did you install it to your device?

**Comment by neoneggplant** [comment] 2016-12-15 05:10
@AppleManPS3 @Shugabuga read the documentation on http://lucasjackson.me/index.php/EggShell/

**Closed** 2016-12-15 05:10 UTC
