### ISSUE TITLE
Shell has a lot of errors.

### ISSUE THREAD

**Issue by mineo210** [neoneggplant/EggShell#38] opened 2017-03-08 16:31 UTC
There is a lot of errors on my sessions.. some commands either doesn't work or when commands are executed there will be a blank space and nothing happens. Netcat is working fine with no errors. I thought first it was some mistake I made on the script for the rubber ducky but It seems it isn't.
Thanks for reading. Hope this gets resolved :)

**Comment by neoneggplant** [comment] 2017-03-08 17:44
which commands specifically?

**Comment by neoneggplant** [comment] 2017-03-08 17:44
I made some major changes with communication, It may still be a little buggy

**Comment by mineo210** [comment] 2017-03-08 17:58
@neoneggplant mainly "ls" "picture" but others work. sometimes the others will bug a bit like "rm" or "cd" and the connection will be delayed.

**Comment by neoneggplant** [comment] 2017-03-08 17:58
which version number are you using?

**Comment by mineo210** [comment] 2017-03-08 17:59
@neoneggplant 2.0.9.9

**Comment by neoneggplant** [comment] 2017-03-08 17:59
what happens when you use picture and ls?

**Comment by neoneggplant** [comment] 2017-03-08 18:01
<img width="457" alt="screen shot 2017-03-08 at 1 00 37 pm" src="https://cloud.githubusercontent.com/assets/12518571/23716731/44329530-03ff-11e7-9108-91fe196893a8.png">
I can't seem to recreate an error

**Comment by mineo210** [comment] 2017-03-08 18:01
@neoneggplant ill send a picture, it happen to my latest victims

**Comment by mineo210** [comment] 2017-03-08 18:02
it happens on both mac and windows

**Comment by mineo210** [comment] 2017-03-08 18:03
this picture is on a one of the real targets to the ip will be displayed :/

**Comment by mineo210** [comment] 2017-03-08 18:03
https://gyazo.com/91a0d2a571a36b6f0c6912699ac977ce

**Comment by mineo210** [comment] 2017-03-08 18:04
@neoneggplant oh now it says error when I do picture

**Comment by neoneggplant** [comment] 2017-03-08 18:05
@mineo210 can you git pull, just to make sure your all caught up with the latest binaries?

**Comment by mineo210** [comment] 2017-03-08 18:05
https://gyazo.com/a8f83ff64da43949df8829cb27361f14

**Comment by mineo210** [comment] 2017-03-08 18:06
@neoneggplant tho netcat works fine with "ls"

**Comment by mineo210** [comment] 2017-03-08 18:08
@neoneggplant https://gyazo.com/f9c61fa4e1a6b2e13bc65b43ac98d :((

**Comment by neoneggplant** [comment] 2017-03-08 18:09
hm, try re downloading eggshell completely, maybe something is wrong with your downloaded version

**Comment by mineo210** [comment] 2017-03-08 18:11
@neoneggplant https://gyazo.com/34f667c3a0141a6da3cb36996467a25f  ?!

**Comment by neoneggplant** [comment] 2017-03-08 18:13
system shell is still in progress, occasionally that will happen

**Comment by neoneggplant** [comment] 2017-03-08 18:14
but ls is causing crashes?

**Comment by mineo210** [comment] 2017-03-08 18:16
@neoneggplant yeah and download doesn't seem to work right now for me and system commands like screencapture

**Comment by mineo210** [comment] 2017-03-08 18:18
ls is the only one the outputs "something went wrong" others now "[*] Error" usally it only comes a blank space and no green text of the victims shell

**Comment by neoneggplant** [comment] 2017-03-08 18:39
did you try re downloading eggshell?

**Comment by neoneggplant** [comment] 2017-03-08 18:40
<img width="327" alt="screen shot 2017-03-08 at 1 40 16 pm" src="https://cloud.githubusercontent.com/assets/12518571/23718264/cb981be4-0404-11e7-91e8-e7e26c8ba715.png">
it is working for me

**Comment by mineo210** [comment] 2017-03-08 18:43
@neoneggplant if I maybe like you said fully remove it and then reclone it will work

**Comment by mineo210** [comment] 2017-03-08 18:44
@neoneggplant what display do you have? thats some high res lol, does it work if you make the screenshot silent with -x for you?

**Comment by neoneggplant** [comment] 2017-03-08 18:52
<img width="496" alt="screen shot 2017-03-08 at 1 51 22 pm" src="https://cloud.githubusercontent.com/assets/12518571/23718660/589199e8-0406-11e7-8faf-7fcda6dfa73c.png">
yup, its working, and yeah, try recloning

**Comment by mineo210** [comment] 2017-03-08 18:53
@neoneggplant alright

**Comment by mineo210** [comment] 2017-03-08 18:56
@neoneggplant I recloned now and "ls" still doesn't work :((

**Comment by mineo210** [comment] 2017-03-08 18:59
@neoneggplant Now I actually think there's something wrong with the "Payload" cause I think the script didn't fully complete when I was inside of single user mode it just shut down after like 10 seconds.. usually takes 30 secs with the rubberducky

**Comment by mineo210** [comment] 2017-03-08 19:00
@neoneggplant do you think it's a better idea if I remove the content it installed via single user mode and add the persistence command instead?

**Comment by neoneggplant** [comment] 2017-03-08 19:13
are the same commands not working still?

**Comment by neoneggplant** [comment] 2017-03-08 19:13
and what do you mean by removing the content via single user mode?

**Comment by neoneggplant** [comment] 2017-03-08 19:16
I am going to make ls use the system ls instead

**Comment by mineo210** [comment] 2017-03-08 19:17
the rubberducky installed a launchagent inside of single user mode when you do "cmd+s" when you restart the mac.. what if thats the issue

**Comment by neoneggplant** [comment] 2017-03-08 19:18
maybe, if it cant get the current working directory, that may be what is causing ls to fail

**Comment by mineo210** [comment] 2017-03-08 19:18
the same commands make the same as before.. tho some of my victim has no errors

**Comment by mineo210** [comment] 2017-03-08 19:18
tho ls work sometimes when you do cd to something so yeah probably

**Comment by neoneggplant** [comment] 2017-03-08 19:44
when you get a connection, if you run pwd first, what does it say?

**Comment by mineo210** [comment] 2017-03-08 19:45
@neoneggplant it says "/"

**Comment by mineo210** [comment] 2017-03-08 19:45
because I'm root

**Comment by neoneggplant** [comment] 2017-03-08 19:55
try to obtain the crash logs of espl if you can on the target

**Comment by mineo210** [comment] 2017-03-08 19:57
wait what?

**Comment by mineo210** [comment] 2017-03-08 19:57
what crash logs?

**Comment by neoneggplant** [comment] 2017-03-08 20:02
~/Library/Logs/DiagnosticReports/ and they should start with espl

**Comment by neoneggplant** [comment] 2017-03-08 20:03
I found the cause of screenshot to crash, in the log it says Application Specific Information:
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid parameter not satisfying: cgImage != NULL'
terminating with uncaught exception of type NSException
abort() called

**Comment by mineo210** [comment] 2017-03-08 20:06
i was able to find the espl crash logs.. should I try to download them?

**Comment by mineo210** [comment] 2017-03-08 20:07
it worked download the latest one

**Comment by mineo210** [comment] 2017-03-08 20:09
@neoneggplant what should i look into in the log?

**Comment by mineo210** [comment] 2017-03-08 20:10
@neoneggplant do you know what it means? the one you found about the screenshot ??

**Comment by neoneggplant** [comment] 2017-03-08 20:22
did you download the recent one?

**Comment by neoneggplant** [comment] 2017-03-08 20:22
I made a change where it crashed for screenshot, tested and screenshot works now

**Comment by neoneggplant** [comment] 2017-03-08 20:22
can you try?

**Comment by mineo210** [comment] 2017-03-08 20:25
ok

**Comment by mineo210** [comment] 2017-03-08 20:29
fuck it doesnt work I get this.. i typed screenshot wrong becasue im lazy lol https://gyazo.com/16bc6686598e24b901a63f744a9f0c6e

**Comment by neoneggplant** [comment] 2017-03-08 20:45
did you get the latest commit with the updated binary?

**Comment by neoneggplant** [comment] 2017-03-08 20:45
also, I am about to push another update, all bug fixes, if the command length is 14, the padding would be messed up

**Comment by mineo210** [comment] 2017-03-08 20:47
@neoneggplant Awesome! I did git pull isn't that enough ??

**Comment by mineo210** [comment] 2017-03-08 20:48
@neoneggplant btw I'm really thankful you're helping me :))

**Comment by mineo210** [comment] 2017-03-08 20:56
@neoneggplant i got the latest log what now?!

**Comment by neoneggplant** [comment] 2017-03-08 20:58
can you past the log so I can see the uncaught exception message?

**Comment by mineo210** [comment] 2017-03-08 21:01
the espl?

**Comment by neoneggplant** [comment] 2017-03-08 21:33
yes

**Comment by neoneggplant** [comment] 2017-03-08 21:45
just pushed a fix for rm on macOS

**Comment by neoneggplant** [comment] 2017-03-08 21:46
I am going to keep ls in espl, is it still broken after the padding bugs I fixed?

**Comment by mineo210** [comment] 2017-03-08 21:49
oh ill send the whole crash log its pretty long?!.. im gonna update now :))

**Comment by neoneggplant** [comment] 2017-03-08 21:50
yeah just upload the file

**Comment by mineo210** [comment] 2017-03-08 21:52
[espl_2017-03-08-204548_kevins-MacBook-Air-2.txt](https://github.com/neoneggplant/EggShell/files/829069/espl_2017-03-08-204548_kevins-MacBook-Air-2.txt)

**Comment by mineo210** [comment] 2017-03-08 21:53
open it on sublime its way easier to read

**Comment by mineo210** [comment] 2017-03-08 21:54
ill try to test this tomorrow no clients are on right now :/

**Comment by neoneggplant** [comment] 2017-03-08 22:16
alright

**Comment by mineo210** [comment] 2017-03-09 20:36
@neoneggplant still doesn't work that good but here's the weird thing everything works fine until i first "cd" to something.. but if I do "cd .." back to where i was more than half of the commands will crash the shell :/

**Comment by neoneggplant** [comment] 2017-03-09 20:44
hmmm, weird, try to isolate the error and get as much info as you can

**Comment by neoneggplant** [comment] 2017-03-09 20:45
find the cd command that can be tested to get the same crash each time and which specific commands would crash the shell

**Comment by neoneggplant** [comment] 2017-03-09 20:45
is it only cd that causes it?

**Comment by mineo210** [comment] 2017-03-10 06:31
@neoneggplant oh sorry I meant that the only command that works is "cd" at first and if you "cd" to something all of the commands will work but if you "cd .." back it will be the same as before that 70 % of the commands will crash or either just dosent work

**Comment by neoneggplant** [comment] 2017-03-10 18:31
do you have screenshots of this process?

**Comment by mineo210** [comment] 2017-03-10 21:33
@neoneggplant I can make a gif

**Comment by neoneggplant** [comment] 2017-03-10 22:10
yeah thats fine

**Comment by mineo210** [comment] 2017-03-11 12:44
1 example https://gyazo.com/b5cf0aa287974b58f626fa21eae63990

**Comment by neoneggplant** [comment] 2017-03-23 00:48
try the new release, let me know if you still have issues

**Comment by mineo210** [comment] 2017-03-23 09:58
Will do!

**Comment by neoneggplant** [comment] 2017-03-31 17:57
still having problems?

**Comment by mineo210** [comment] 2017-04-03 22:31
haven't sadly gotten the chance to test it on my most glitches victim since he hasn't been online when I listen for connections and I've been moving to a new apartment so wi-fi has been a problem.. Otherwise every other victim is working.

**Comment by neoneggplant** [comment] 2017-04-04 01:52
ok, when you say victim, I assume you mean your own target victim machines

**Comment by mineo210** [comment] 2017-04-04 06:26
Some of my classmates and they know it.
I've been doing before without a guy knowing but it was a request from some friend when I first started using eggshell otherwise I'm not using it for illegal activities.

**Comment by neoneggplant** [comment] 2017-04-04 17:25
ok, because I can only help if you are using with user consent or on computers you own

**Closed** 2017-04-07 19:09 UTC
